Reference:
  # don't change these unless you are not using resources directory inside this repository
  fasta: "./resources/GRCh38_full_analysis_set_plus_decoy_hla.fa"
  KIR_regions_bed: "./resources/kir_regions.bed"
  fasta_2: "./resources/ref_with_utr_extended.fa"
  KIR_alleles: "./resources/kir_gen_new_mod_with_utr_extended.fasta"
  KIR_alleles_bed: "./resources/kir_allele_names_new_kir_only.bed"
  exon_bed: "./resources/annotations_mod_with_utr_extended_exon.bed"
  intron_bed: "./resources/annotations_mod_with_utr_extended_intron.bed"
  utr_bed: "./resources/annotations_mod_with_utr_extended_utr.bed"
  msa_path: "./resources/msa_after_utr_extension"
  msa_mappings_path:  "./resources/msa_after_utr_extension/msa_mappings"
  Allele_list: "./resources/Allelelist.txt"
  rep:  "./resources/allele_representatives_new_kir.pkl"

Samples:
  # Output directory for results
  samples_dir: "path/to/output directory"  # e.g., "./output"
  # Sample specification:
   #List samples directly (for small batches)
  # option1 on is to specify fastq files
  sample_fastqs:
    # Format: "sample_name": ["path/to/read1.fastq.gz", "path/to/read2.fastq.gz"]
    # Example:
    # "ERR3988826": ["/gpfs/project/yogah100/kir/real_data/ERR3988826/ERR3988826_fix_pass_1.fastq.gz", "/gpfs/project/yogah100/kir/real_data/ERR3988826/ERR3988826_fix_pass_2.fastq.gz"]
    # "sample_2": ["./data/sample_2_R1.fastq.gz", "./data/sample_2_R2.fastq.gz"]
  # option2 on is to specify cram or bam files mapped to GRCh38 reference, and the pipeline will extract reads from KIR regions and convert them to fastq files for processing
    # Example:
    #"ERR3239454": [ "/gpfs/project/yogah100/cram_files/evaluation/ERR3239454/NA19239.final.cram" ]
# External tools
bwa_path: null  # BWA-MEM2 executable, e.g., "/opt/bwa-mem2/bwa-mem2"
# Optional parameters
parameters:
  threads: 4  # maximum number of threads for parallel processing

background_region: "chr17:38000000-40000000" # coordinates on GRCh38 to use as beackground to calculate error rates and depth


