Reference:
  fasta:  "/gpfs/project/yogah100/cram_files/resources/GRCh38_full_analysis_set_plus_decoy_hla.fa"
  KIR_regions_bed: "/gpfs/project/yogah100/cram_files/resources/kir_regions.bed" # Kir regions coordinate and Chr17 
  fasta_2: "/gpfs/project/yogah100/cram_files/resources/kir_reference_2025_no_mod_to_3DL3035/ref_with_utr_extended.fa"
  KIR_alleles: '/gpfs/project/yogah100/cram_files/resources/kir_reference_2025_no_mod_to_3DL3035/kir_gen_new_mod_with_utr_extended.fasta'
  KIR_alleles_bed: "/gpfs/project/yogah100/kir/resources/kir_reference_2025/kir_allele_names_new_kir_only.bed"
  exon_bed: "/gpfs/project/yogah100/cram_files/resources/kir_reference_2025_no_mod_to_3DL3035/annotations_mod_with_utr_extended_exon.bed"
  intron_bed: "/gpfs/project/yogah100/cram_files/resources/kir_reference_2025_no_mod_to_3DL3035/annotations_mod_with_utr_extended_intron.bed"
  utr_bed: "/gpfs/project/yogah100/cram_files/resources/kir_reference_2025_no_mod_to_3DL3035/annotations_mod_with_utr_extended_utr.bed"
  msa_path: "/gpfs/project/yogah100/cram_files/resources/kir_reference_2025_no_mod_to_3DL3035/msa_after_utr_extension"
  msa_mappings_path: "/gpfs/project/yogah100/cram_files/resources/kir_reference_2025_no_mod_to_3DL3035/msa_after_utr_extension/msa_mappings"
  Allele_list: "/gpfs/project/yogah100/cram_files/resources/kir_reference_2025/Allelelist.txt" 
  rep: "/gpfs/project/yogah100/cram_files/resources/kir_reference_2025/allele_representatives_new_kir.pkl" 
Samples:
  samples_dir: "/gpfs/project/yogah100/1000Genome" #output directory
  sample_fastqs:  
        "NA06985": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA06985.final.cram"]
        "NA06986": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA06986.final.cram"]
        "NA06994": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA06994.final.cram"]
        "NA07000": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA07000.final.cram"]
        "NA07037": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA07037.final.cram"]
        "NA07051": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA07051.final.cram"]
        "NA07347": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA07347.final.cram"]
        "NA07357": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA07357.final.cram"]
        "NA10847": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA10847.final.cram"]
        "NA10851": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA10851.final.cram"]
        "NA11829": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA11829.final.cram"]
        "NA11830": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA11830.final.cram"]
        "NA11831": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA11831.final.cram"]
        "NA11832": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA11832.final.cram"]
        "NA11840": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA11840.final.cram"]
        "NA11881": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA11881.final.cram"]
        "NA11894": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA11894.final.cram"]
        "NA11918": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA11918.final.cram"]
        "NA11919": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA11919.final.cram"]
        "NA11931": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA11931.final.cram"]
        "NA11992": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA11992.final.cram"]
        "NA12718": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12718.final.cram"]
        "NA12748": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12748.final.cram"]
        "NA12775": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12775.final.cram"]
        "NA12777": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12777.final.cram"]
        "NA12778": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12778.final.cram"]
        "NA12827": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12827.final.cram"]
        "NA12829": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12829.final.cram"]
        "NA12842": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12842.final.cram"]
        "NA12843": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12843.final.cram"]
        "NA12889": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12889.final.cram"]
        "NA12890": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12890.final.cram"]
        "NA12156": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12156.final.cram"]
        "NA06984": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA06984.final.cram"]
        "NA06989": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA06989.final.cram"]
        "NA07056": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA07056.final.cram"]
        "NA11843": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA11843.final.cram"]
        "NA11892": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA11892.final.cram"]
        "NA11893": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA11893.final.cram"]
        "NA11930": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA11930.final.cram"]
        "NA12058": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12058.final.cram"]
        "NA12249": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12249.final.cram"]
        "NA12272": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12272.final.cram"]
        "NA12273": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12273.final.cram"]
        "NA12275": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12275.final.cram"]
        "NA12282": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12282.final.cram"]
        "NA12283": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12283.final.cram"]
        "NA12286": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12286.final.cram"]
        "NA12287": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12287.final.cram"]
        "NA12340": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12340.final.cram"]
        "NA12341": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12341.final.cram"]
        "NA12342": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12342.final.cram"]
        "NA12347": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12347.final.cram"]
        "NA12348": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12348.final.cram"]



# parameters
threads: 20  # maximum number of threads for parallel processing
max_chunk_gb: 0.5  # target maximum size (GB) per contig chunk for parallel pairing
background_region: "chr17:74000000-76000000" # chr12:10226058-10329608 #
bwa_path:  /gpfs/project/yogah100/Software/bwa-mem2-2.2.1_x64-linux/bwa-mem2
immuannot: /gpfs/project/yogah100/Software/Immuannot/scripts.pub.v3/immuannot.sh
samtools_path: /home/yogah100/miniforge3/envs/medaka2/bin/samtools