Reference:
  fasta:  "/gpfs/project/yogah100/cram_files/resources/GRCh38_full_analysis_set_plus_decoy_hla.fa"
  KIR_regions_bed: "/gpfs/project/yogah100/cram_files/resources/kir_regions.bed" # Kir regions coordinate and Chr17 
  fasta_2: "/gpfs/project/yogah100/cram_files/resources/kir_reference_2025_no_mod_to_3DL3035/ref_with_utr_extended.fa"
  KIR_alleles: '/gpfs/project/yogah100/cram_files/resources/kir_reference_2025_no_mod_to_3DL3035/kir_gen_new_mod_with_utr_extended.fasta'
  KIR_alleles_bed: "/gpfs/project/yogah100/kir/resources/kir_reference_2025/kir_allele_names_new_kir_only.bed"
  exon_bed: "/gpfs/project/yogah100/cram_files/resources/kir_reference_2025_no_mod_to_3DL3035/annotations_mod_with_utr_extended_exon.bed"
  intron_bed: "/gpfs/project/yogah100/cram_files/resources/kir_reference_2025_no_mod_to_3DL3035/annotations_mod_with_utr_extended_intron.bed"
  utr_bed: "/gpfs/project/yogah100/cram_files/resources/kir_reference_2025_no_mod_to_3DL3035/annotations_mod_with_utr_extended_utr.bed"
  msa_path: "/gpfs/project/yogah100/cram_files/resources/kir_reference_2025_no_mod_to_3DL3035/msa_after_utr_extension"
  msa_mappings_path: "/gpfs/project/yogah100/cram_files/resources/kir_reference_2025_no_mod_to_3DL3035/msa_after_utr_extension/msa_mappings"
  Allele_list: "/gpfs/project/yogah100/cram_files/resources/kir_reference_2025/Allelelist.txt" 
  rep: "/gpfs/project/yogah100/cram_files/resources/kir_reference_2025/allele_representatives_new_kir.pkl" 
Samples:
  samples_dir: "/gpfs/project/yogah100/1000Genome" #output directory
  sample_fastqs:        
        "NA12383": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12383.final.cram"]
        "NA12399": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12399.final.cram"]
        "NA12400": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12400.final.cram"]
        "NA12413": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12413.final.cram"]
        "NA12414": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12414.final.cram"]
        "NA12489": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12489.final.cram"]
        "NA12546": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12546.final.cram"]
        "NA12716": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12716.final.cram"]
        "NA12717": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12717.final.cram"]
        "NA12749": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12749.final.cram"]
        "NA12750": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12750.final.cram"]
        "NA12751": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12751.final.cram"]
        "NA12760": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12760.final.cram"]
        "NA12761": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12761.final.cram"]
        "NA12762": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12762.final.cram"]
        "NA12763": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12763.final.cram"]
        "NA12776": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12776.final.cram"]
        "NA12812": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12812.final.cram"]
        "NA12813": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12813.final.cram"]
        "NA12814": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12814.final.cram"]
        "NA12815": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12815.final.cram"]
        "NA12828": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12828.final.cram"]
        "NA12830": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12830.final.cram"]
        "NA12872": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12872.final.cram"]
        "NA12873": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12873.final.cram"]
        "NA12874": ["/gpfs/project/yogah100/1000Genome/1000G/CEU/NA12874.final.cram"]
# parameters
threads: 20  # maximum number of threads for parallel processing
max_chunk_gb: 0.5  # target maximum size (GB) per contig chunk for parallel pairing
background_region: "chr17:74000000-76000000" # chr12:10226058-10329608 #
bwa_path:  /gpfs/project/yogah100/Software/bwa-mem2-2.2.1_x64-linux/bwa-mem2
immuannot: /gpfs/project/yogah100/Software/Immuannot/scripts.pub.v3/immuannot.sh
samtools_path: /home/yogah100/miniforge3/envs/medaka2/bin/samtools