Reference:
  fasta:  "/gpfs/project/yogah100/cram_files/resources/GRCh38_full_analysis_set_plus_decoy_hla.fa"
  KIR_regions_bed: "/gpfs/project/yogah100/cram_files/resources/kir_regions.bed" # Kir regions coordinate and Chr17 
  fasta_2: "/gpfs/project/yogah100/cram_files/resources/kir_reference_2025_no_mod_to_3DL3035/ref_with_utr_extended.fa"
  KIR_alleles: '/gpfs/project/yogah100/cram_files/resources/kir_reference_2025_no_mod_to_3DL3035/kir_gen_new_mod_with_utr_extended.fasta'
  KIR_alleles_bed: "/gpfs/project/yogah100/kir/resources/kir_reference_2025/kir_allele_names_new_kir_only.bed"
  exon_bed: "/gpfs/project/yogah100/cram_files/resources/kir_reference_2025_no_mod_to_3DL3035/annotations_mod_with_utr_extended_exon.bed"
  intron_bed: "/gpfs/project/yogah100/cram_files/resources/kir_reference_2025_no_mod_to_3DL3035/annotations_mod_with_utr_extended_intron.bed"
  utr_bed: "/gpfs/project/yogah100/cram_files/resources/kir_reference_2025_no_mod_to_3DL3035/annotations_mod_with_utr_extended_utr.bed"
  msa_path: "/gpfs/project/yogah100/cram_files/resources/kir_reference_2025_no_mod_to_3DL3035/msa_after_utr_extension"
  msa_mappings_path: "/gpfs/project/yogah100/cram_files/resources/kir_reference_2025_no_mod_to_3DL3035/msa_after_utr_extension/msa_mappings"
  Allele_list: "/gpfs/project/yogah100/cram_files/resources/kir_reference_2025/Allelelist.txt" 
  rep: "/gpfs/project/yogah100/cram_files/resources/kir_reference_2025/allele_representatives_new_kir.pkl" 
Samples:
  samples_dir: "/gpfs/project/yogah100/1000Genome" #output directory
  sample_fastqs:  
        "NA18488": ["/gpfs/project/yogah100/1000Genome/1000G/YRI/NA18488.final.cram"]
        "NA18867": ["/gpfs/project/yogah100/1000Genome/1000G/YRI/NA18867.final.cram"]
        "NA18868": ["/gpfs/project/yogah100/1000Genome/1000G/YRI/NA18868.final.cram"]
        "NA18873": ["/gpfs/project/yogah100/1000Genome/1000G/YRI/NA18873.final.cram"]
        "NA18908": ["/gpfs/project/yogah100/1000Genome/1000G/YRI/NA18908.final.cram"]
        "NA19222": ["/gpfs/project/yogah100/1000Genome/1000G/YRI/NA19222.final.cram"]
        "NA18910": ["/gpfs/project/yogah100/1000Genome/1000G/YRI/NA18910.final.cram"]
        "NA18917": ["/gpfs/project/yogah100/1000Genome/1000G/YRI/NA18917.final.cram"]
        "NA18923": ["/gpfs/project/yogah100/1000Genome/1000G/YRI/NA18923.final.cram"]
        "NA18924": ["/gpfs/project/yogah100/1000Genome/1000G/YRI/NA18924.final.cram"]
        "NA18933": ["/gpfs/project/yogah100/1000Genome/1000G/YRI/NA18933.final.cram"]
        "NA18934": ["/gpfs/project/yogah100/1000Genome/1000G/YRI/NA18934.final.cram"]
        "NA19092": ["/gpfs/project/yogah100/1000Genome/1000G/YRI/NA19092.final.cram"]
        "NA19095": ["/gpfs/project/yogah100/1000Genome/1000G/YRI/NA19095.final.cram"]
        "NA19096": ["/gpfs/project/yogah100/1000Genome/1000G/YRI/NA19096.final.cram"]
        "NA19107": ["/gpfs/project/yogah100/1000Genome/1000G/YRI/NA19107.final.cram"]
        "NA19113": ["/gpfs/project/yogah100/1000Genome/1000G/YRI/NA19113.final.cram"]
        "NA19117": ["/gpfs/project/yogah100/1000Genome/1000G/YRI/NA19117.final.cram"]
        "NA19118": ["/gpfs/project/yogah100/1000Genome/1000G/YRI/NA19118.final.cram"]
        #"NA19121": ["/gpfs/project/yogah100/1000Genome/1000G/YRI/NA19121.final.cram"]  # there is a problem
        "NA19130": ["/gpfs/project/yogah100/1000Genome/1000G/YRI/NA19130.final.cram"]
        "NA19146": ["/gpfs/project/yogah100/1000Genome/1000G/YRI/NA19146.final.cram"]
        "NA19149": ["/gpfs/project/yogah100/1000Genome/1000G/YRI/NA19149.final.cram"]
        #"NA19175": ["/gpfs/project/yogah100/1000Genome/1000G/YRI/NA19175.final.cram"] # there is a problem

        


# parameters
threads: 20  # maximum number of threads for parallel processing
max_chunk_gb: 0.5  # target maximum size (GB) per contig chunk for parallel pairing
background_region: "chr17:74000000-76000000" # chr12:10226058-10329608 #
bwa_path:  /gpfs/project/yogah100/Software/bwa-mem2-2.2.1_x64-linux/bwa-mem2
immuannot: /gpfs/project/yogah100/Software/Immuannot/scripts.pub.v3/immuannot.sh
samtools_path: /home/yogah100/miniforge3/envs/medaka2/bin/samtools